version: "3.7"
services:

  webserver:
    container_name: webserver
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/srv
      - ./default.conf:/etc/nginx/conf.d/default.conf
